export const CartActionTypes = {
  TOGGLE_CART:'TOGGLE_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_ITEM: 'DELETE_ITEM',
  INCREAMENT_ITEM: 'INCREAMENT_ITEM',
  DECREAMENT_ITEM: 'DECREAMENT_ITEM',
};
